export const DISPLAY_COMPONENT_GET_DATA = "DISPLAY_COMPONENT_GET_DATA";
export const DISPLAY_COMPONENT_GET_DATA_SUCCESS = "DISPLAY_COMPONENT_GET_DATA_SUCCESS";
export const DISPLAY_COMPONENT_GET_DATA_FAIL = "DISPLAY_COMPONENT_GET_DATA_FAIL";
